Dragon CTF: Harmony Chat
TFNS/writeups pull request #29
Opened 2020-11-24 01:40 UTC by posix-lee

hoi hoi

2020-11-25 22:52 UTC, Pharisaeus requested changes
In general I'm more familiar with reading the description `before` and not `after` the code snippet. It makes it easier to understand the code, once I already know what it's supposed to do and what I'm looking at.

2020-11-25 22:52 UTC, Pharisaeus commented on 2020-11-22-DragonCTF/harmony_chat/README.md
> +Harmony Chat is Web Challenge implemented Chat application.
implementing

2020-11-25 22:52 UTC, Pharisaeus commented on 2020-11-22-DragonCTF/harmony_chat/README.md
> +`javascript-serializer` is supported to deserialize function similar with `node-serialize` known as one of vulnerable module.
one of vulnerable modules

2020-11-25 22:52 UTC, Pharisaeus commented on 2020-11-22-DragonCTF/harmony_chat/README.md
> +After deserialized, the csp-report property of result used for constructing report which is string type.
Sorry, I got stroke trying to parse this sentence :(

2020-11-25 22:52 UTC, Pharisaeus commented on 2020-11-22-DragonCTF/harmony_chat/README.md
> +from the [docs](https://github.com/wix-incubator/javascript-serializer), We could know `javascript-serializer` allows to constructor object by setting `___js-to-json-class___` property.
allows to assign constructor? allows to create constructor?

2020-11-25 22:52 UTC, Pharisaeus commented on 2020-11-22-DragonCTF/harmony_chat/README.md
> +but since there's ip restriction for the handleReport function.
but there's ip restriction... (no `since`)

2020-11-26 08:32 UTC, Pharisaeus approved these changes

2020-11-26 08:37 UTC, merged

2020-11-27 00:47 UTC, XeR commented
@posix-lee ideally we want to have a single commit per challenge.
When your merge request consists of **a single challenge** but multiple commits (like here), you should squash it.
When your merge request consists of **multiple challenges**, one of which has at least one "fix" commit, you should make it a fixup.
If you need help, feel free to ask me and I'll help you get your writeups merged :-)

2020-11-27 01:33 UTC, posix-lee commented
@XeR Sorry bro, I didn't expected the difference of Squash merge and Rebase merge...
btw do you believe revert & remerge will be good choice?

2020-11-27 09:23 UTC, XeR commented
Don't worry. It's not a big deal.
I just wanted to tell you for the next time ;-)